image:
  repository: lam1051999/trino-custom
  tag: 470
  pullPolicy: IfNotPresent

catalogs:
  tpch: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds: |
    connector.name=tpcds
    tpcds.splits-per-node=4
  delta_lake: |
    connector.name=delta_lake
    hive.metastore.uri=thrift://hive-metastore.data-platform.svc.cluster.local:9083
    fs.native-s3.enabled=true
    delta.hive-catalog-name=delta_lake
    delta.enable-non-concurrent-writes=true
    delta.register-table-procedure.enabled=true
    s3.aws-access-key=minio
    s3.aws-secret-key=minio123
    s3.endpoint=https://minio.data-platform.svc.cluster.local:443
    s3.path-style-access=true
    s3.region=us-east-1