apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-create-hive-table
  namespace: data-platform
spec:
  sparkConf:
    spark.sql.extensions: io.delta.sql.DeltaSparkSessionExtension
    spark.sql.catalog.spark_catalog: org.apache.spark.sql.delta.catalog.DeltaCatalog
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: LTranData/spark-create-hive-table:3.5.3
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///app/create_table.py
  sparkVersion: 3.5.3
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    memory: "512m"
    labels:
      version: 3.5.3
    serviceAccount: spark-operator-spark
    env:
      - name: AWS_REGION
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: AWS_REGION
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: AWS_SECRET_ACCESS_KEY
      - name: ENDPOINT
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: ENDPOINT
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.5.3
    env:
      - name: AWS_REGION
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: AWS_REGION
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: AWS_SECRET_ACCESS_KEY
      - name: ENDPOINT
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: ENDPOINT